import Link from 'next/link';
import { ArrowUpRight, Building2, CheckCircle2, Files, LockKeyhole, Network, ShieldCheck, UsersRound } from 'lucide-react';
import { getServerAuthContext } from '@/lib/server-auth';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Avatar } from '@/components/ui/avatar';

const shortcuts = [{ label: 'Organizations', href: '/admin/organizations', permission: 'organizations.view', icon: Building2 }, { label: 'Franchises', href: '/admin/franchises', permission: 'franchises.view', icon: Network }, { label: 'Partner agencies', href: '/admin/partner-agencies', permission: 'partner_agencies.view', icon: Files }, { label: 'Users', href: '/admin/users', permission: 'users.view', icon: UsersRound }, { label: 'Positions', href: '/admin/positions', permission: 'positions.view', icon: ShieldCheck }, { label: 'Permissions', href: '/admin/permissions', permission: 'permissions.view', icon: LockKeyhole }];

export default async function DashboardPage() {
  const context = await getServerAuthContext();
  if (!context) return null;
  const available = shortcuts.filter((item) => context.permissions.includes(item.permission));
  return <main className="page-shell fade-up"><div className="grid gap-8 lg:grid-cols-[1.25fr_0.75fr]"><section className="relative overflow-hidden rounded-lg bg-charcoal p-8 text-white shadow-lift md:p-10"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full border-[28px] border-brand/20" /><div className="relative"><p className="eyebrow text-brand">Your workspace</p><h1 className="mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-[-0.05em] md:text-5xl">Good to see you, {context.user.full_name.split(' ')[0]}.</h1><p className="mt-5 max-w-lg text-sm leading-7 text-white/65">Here is the current context for your Directors workspace. Choose a module below to continue your work.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Badge variant="success"><CheckCircle2 size={13} className="mr-1.5" /> Active session</Badge><span className="text-xs text-white/50">Permission-aware workspace</span></div></div></section><Card><CardContent><p className="eyebrow">Current context</p><div className="mt-5 flex items-center gap-4"><Avatar name={context.user.full_name} size="lg" /><div><h2 className="font-semibold text-ink">{context.user.full_name}</h2><p className="mt-1 text-sm text-muted">{context.user.email}</p></div></div><div className="mt-7 space-y-4 border-t border-line pt-5"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">Organization</p><p className="mt-1 text-sm font-semibold text-ink">{context.organization?.name ?? 'Not assigned'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">Position</p><p className="mt-1 text-sm font-semibold text-ink">{context.position?.name ?? 'No Position assigned'}</p></div></div></CardContent></Card></div><section className="mt-10"><div className="flex items-end justify-between"><div><p className="eyebrow">Available modules</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.03em] text-ink">Move into the work</h2></div><p className="text-sm text-muted">{context.permissions.length} active permissions</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{available.map((item) => { const Icon = item.icon; return <Link key={item.href} href={item.href} className="group rounded-lg border border-line bg-surface p-5 shadow-soft transition hover:-translate-y-0.5 hover:border-brand/50 hover:shadow-lift"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-md bg-brand/10 text-brand"><Icon size={19} /></div><ArrowUpRight size={17} className="text-muted transition group-hover:text-brand" /></div><h3 className="mt-7 font-semibold text-ink">{item.label}</h3><p className="mt-1 text-sm text-muted">Open the {item.label.toLowerCase()} workspace.</p></Link>; })}</div></section></main>;
}
