<?php
declare(strict_types=1);
use App\Core\Container;use App\Core\Database\DatabaseConnectionInterface;use App\Core\DatabaseManager;use App\Modules\Property\Seeds\{PropertyCategoriesSeedPackage,UnitTypesSeedPackage,MeasurementDefinitionsSeedPackage,AttributeDefinitionsSeedPackage,AttributeOptionsSeedPackage,UnitTypeConfigurationsSeedPackage,EgyptGeographySeedPackage};use App\Modules\Property\Services\{PropertyCatalogSeedRunner,PropertyCatalogService,UnitTypeConfigurationService,GeographicLocationService};use App\Providers\AppServiceProvider;
require dirname(__DIR__,2).'/vendor/autoload.php';
function dcheck(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}function derr(callable $f):void{try{$f();}catch(RuntimeException $e){dcheck($e->getMessage()==='SEED_PACKAGE_COLLISION','Unexpected '.$e->getMessage());return;}throw new RuntimeException('Expected SEED_PACKAGE_COLLISION');}
$root=dirname(__DIR__,2);Dotenv\Dotenv::createImmutable($root)->safeLoad();$config=require $root.'/config/database.php';$c=$config['connections']['mysql'];$name='directors_resale_platform_d_seed_test_'.getmypid();dcheck(preg_match('/^directors_resale_platform_d_seed_test_[0-9]+$/D',$name)===1&&$name!==$c['database'],'Unsafe database');$server=new PDO(sprintf('mysql:host=%s;port=%d;charset=utf8mb4',$c['host'],$c['port']),$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$created=false;$db=null;
try{
 dcheck(str_contains((string)$server->query('SELECT VERSION()')->fetchColumn(),'MariaDB'),'Real MariaDB');$server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$created=true;$config['connections']['mysql']['database']=$name;$db=new DatabaseManager($config);$pdo=$db->connection();$files=glob($root.'/database/migrations/*.sql');sort($files);foreach($files as$f)$pdo->exec(file_get_contents($f));
 $box=new Container();(new AppServiceProvider($box,[]))->register();$box->instance(DatabaseConnectionInterface::class,$db);$catalog=$box->make(PropertyCatalogService::class);$configuration=$box->make(UnitTypeConfigurationService::class);$geo=$box->make(GeographicLocationService::class);$runner=$box->make(PropertyCatalogSeedRunner::class);$packages=[PropertyCategoriesSeedPackage::make($catalog),UnitTypesSeedPackage::make($catalog),MeasurementDefinitionsSeedPackage::make($catalog),AttributeDefinitionsSeedPackage::make($catalog),AttributeOptionsSeedPackage::make($catalog),UnitTypeConfigurationsSeedPackage::make($catalog,$configuration),EgyptGeographySeedPackage::make($geo)];$seven=$packages[6];$rows=EgyptGeographySeedPackage::rows();
 dcheck(count($rows)===28&&count(array_unique(array_column($rows,0)))===28,'Matrix');$apply=[];foreach($packages as$p){$apply[]='APPLY '.$p->key;$apply[]='DONE '.$p->key;}$skip=array_map(fn($p)=>'SKIP '.$p->key,$packages);dcheck($runner->run(array_reverse($packages))===$apply,'Order');
 $all=$geo->listLocations(['limit'=>100]);dcheck(count($all)===28,'Count');$by=array_column($all,null,'code');$egypt=$by['EGYPT'];dcheck($egypt['name_en']==='Egypt'&&$egypt['name_ar']==='مصر'&&$egypt['location_type']==='COUNTRY'&&$egypt['parent_id']===null&&$egypt['status']==='active'&&$egypt['provenance']==='SYSTEM_SEED','Egypt');foreach(array_slice($rows,1)as$row){$x=$by[$row[0]]??null;dcheck($x!==null&&$x['name_en']===$row[1]&&$x['name_ar']===$row[2]&&$x['location_type']==='GOVERNORATE'&&$x['parent_id']===$egypt['id']&&$x['status']==='active'&&$x['provenance']==='SYSTEM_SEED','Governorate '.$row[0]);}foreach(['CITY','AREA','DISTRICT']as$type)dcheck($geo->listLocations(['location_type'=>$type])===[],'No '.$type);dcheck((int)$pdo->query('SELECT COUNT(*) FROM developers')->fetchColumn()===0&&(int)$pdo->query('SELECT COUNT(*) FROM projects')->fetchColumn()===0&&(int)$pdo->query('SELECT COUNT(*) FROM project_phases')->fetchColumn()===0,'No development');dcheck(array_column($pdo->query('SELECT seed_key FROM property_catalog_seed_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC),'seed_key')===array_map(fn($p)=>$p->key,$packages),'Ledger');
 $before=$pdo->query('SELECT * FROM geographic_locations ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);dcheck($runner->run($packages)===$skip&&$pdo->query('SELECT * FROM geographic_locations ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$before,'Rerun');$cairo=$by['CAIRO'];$geo->updateLocation($cairo['id'],['name_en'=>'Admin edit']);$changed=$pdo->query('SELECT * FROM geographic_locations ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);dcheck($runner->run($packages)===$skip&&$pdo->query('SELECT * FROM geographic_locations ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$changed,'Admin edit');
 $pdo->exec('DELETE FROM property_catalog_seed_versions WHERE seed_key='.$pdo->quote($seven->key));$geo->updateLocation($cairo['id'],['name_en'=>'Cairo']);dcheck($runner->run([$seven])===['APPLY '.$seven->key,'DONE '.$seven->key],'Compatible recovery');
 $pdo->exec('DELETE FROM geographic_locations WHERE parent_id IS NOT NULL');$pdo->exec('DELETE FROM geographic_locations');$pdo->exec('DELETE FROM property_catalog_seed_versions');$runner->run(array_slice($packages,0,6));$geo->createLocation(['code'=>'EGYPT','name_en'=>'Admin','name_ar'=>'Admin','location_type'=>'COUNTRY']);derr(fn()=>$runner->run([$seven]));dcheck((int)$pdo->query('SELECT COUNT(*) FROM property_catalog_seed_versions WHERE seed_key='.$pdo->quote($seven->key))->fetchColumn()===0,'Collision ledger');
 $reset=function()use($pdo,$runner,$packages):void{$pdo->exec('DELETE FROM geographic_locations WHERE parent_id IS NOT NULL');$pdo->exec('DELETE FROM geographic_locations');$pdo->exec('DELETE FROM property_catalog_seed_versions WHERE seed_key=\'007-egypt-geography\'');$runner->run(array_slice($packages,0,6));};
 $reset();$egypt=$geo->createLocation(['code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);$admin=$geo->createLocation(['code'=>'CAIRO','name_en'=>'Admin','name_ar'=>'Admin','location_type'=>'GOVERNORATE','parent_id'=>$egypt['id']]);derr(fn()=>$runner->run([$seven]));dcheck($admin['provenance']==='SYSTEM_ADMIN'&&$geo->findLocation($admin['id'])['provenance']==='SYSTEM_ADMIN','Admin governorate takeover');
 $reset();$bad=$geo->createLocation(['code'=>'EGYPT','name_en'=>'Bad','name_ar'=>'مصر','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);derr(fn()=>$runner->run([$seven]));dcheck($geo->findLocation($bad['id'])['name_en']==='Bad','Bad Egypt corrected');
 $reset();$geo->createLocation(['code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);$bad=$geo->createLocation(['code'=>'CAIRO','name_en'=>'Cairo','name_ar'=>'القاهرة','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);derr(fn()=>$runner->run([$seven]));dcheck($geo->findLocation($bad['id'])['location_type']==='COUNTRY','Bad level corrected');
 $reset();$egypt=$geo->createLocation(['code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);$other=$geo->createLocation(['code'=>'OTHER_COUNTRY','name_en'=>'Other','name_ar'=>'Other','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);$bad=$geo->createLocation(['code'=>'CAIRO','name_en'=>'Cairo','name_ar'=>'القاهرة','location_type'=>'GOVERNORATE','parent_id'=>$other['id'],'provenance'=>'SYSTEM_SEED']);derr(fn()=>$runner->run([$seven]));dcheck($geo->findLocation($bad['id'])['parent_id']===$other['id'],'Bad parent corrected');
 $reset();$geo->createLocation(['code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر','location_type'=>'COUNTRY','provenance'=>'SYSTEM_SEED']);$late=$geo->createLocation(['code'=>'MATROUH','name_en'=>'Admin','name_ar'=>'Admin','location_type'=>'GOVERNORATE','parent_id'=>$geo->listLocations(['location_type'=>'COUNTRY'])[0]['id']]);derr(fn()=>$runner->run([$seven]));dcheck((int)$pdo->query('SELECT COUNT(*) FROM geographic_locations')->fetchColumn()===2,'Late rollback partial geography');dcheck((int)$pdo->query('SELECT COUNT(*) FROM property_catalog_seed_versions WHERE seed_key=\'007-egypt-geography\'')->fetchColumn()===0,'Late rollback ledger');dcheck((int)$pdo->query('SELECT COUNT(*) FROM property_catalog_seed_versions')->fetchColumn()===6&&(int)$pdo->query('SELECT COUNT(*) FROM unit_type_configuration_versions WHERE status=\'active\'')->fetchColumn()===20,'Earlier packages persistence');
 $pdo->exec('DELETE FROM geographic_locations WHERE parent_id IS NOT NULL');$pdo->exec('DELETE FROM geographic_locations');$pdo->exec('DELETE FROM property_catalog_seed_versions');$pdo->exec('DELETE FROM unit_type_attribute_rules');$pdo->exec('DELETE FROM unit_type_measurement_rules');$pdo->exec('DELETE FROM unit_type_configuration_versions');$pdo->exec('DELETE FROM attribute_options');$pdo->exec('DELETE FROM attribute_definitions');$pdo->exec('DELETE FROM measurement_definitions');$pdo->exec('DELETE FROM unit_types');$pdo->exec('DELETE FROM property_categories');
 $cli=function()use($root,$name,$c):array{$env=['DB_CONNECTION'=>'mysql','DB_DATABASE'=>$name,'DB_HOST'=>$c['host'],'DB_PORT'=>$c['port'],'DB_USERNAME'=>$c['username'],'DB_PASSWORD'=>$c['password']];$code='$_ENV = array_replace($_ENV, '.var_export($env,true).'); require '.var_export($root.'/bin/seed-property-catalog.php',true).';';$p=proc_open([PHP_BINARY,'-r',$code],[1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);dcheck(is_resource($p),'CLI unavailable');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);dcheck(proc_close($p)===0&&$err==='','CLI failure');return preg_split('/\R/',trim($out));};dcheck($cli()===$apply,'CLI first');dcheck($cli()===$skip,'CLI second');
 echo "BF014 D Egypt geography package MariaDB acceptance: PASS\n";
}finally{if($db!==null&&$db->connection()->inTransaction())$db->rollback();if($created)$server->exec("DROP DATABASE `$name`");}
