<?php
declare(strict_types=1);
use App\Core\Container;use App\Core\Database\DatabaseConnectionInterface;use App\Core\DatabaseManager;use App\Modules\Property\Seeds\{PropertyCategoriesSeedPackage,UnitTypesSeedPackage,MeasurementDefinitionsSeedPackage,AttributeDefinitionsSeedPackage,AttributeOptionsSeedPackage,UnitTypeConfigurationsSeedPackage,EgyptGeographySeedPackage};use App\Modules\Property\Services\{PropertyCatalogSeedRunner,PropertyCatalogService,UnitTypeConfigurationService,GeographicLocationService,DevelopmentCatalogService,PropertyFormProjectionService};use App\Providers\AppServiceProvider;use Dotenv\Dotenv;
require dirname(__DIR__,2).'/vendor/autoload.php';
function c6ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}function c6eq(mixed $a,mixed $b,string $m):void{c6ok($a===$b,$m.': '.var_export($a,true));}function c6exec(PDO $p):int{$e=$p->getAttribute(PDO::ATTR_EMULATE_PREPARES);$p->setAttribute(PDO::ATTR_EMULATE_PREPARES,true);try{return(int)$p->query("SHOW SESSION STATUS LIKE 'Com_stmt_execute'")->fetch()['Value'];}finally{$p->setAttribute(PDO::ATTR_EMULATE_PREPARES,$e);}}
$root=dirname(__DIR__,2);Dotenv::createImmutable($root)->safeLoad();$config=require $root.'/config/database.php';$connection=$config['connections']['mysql'];$name='directors_resale_platform_bf014_core_form_test_'.getmypid();$safe=static fn(string $n):bool=>preg_match('/^directors_resale_platform_bf014_core_form_test_[0-9]+$/D',$n)===1;$server=new PDO(sprintf('mysql:host=%s;port=%d;charset=utf8mb4',$connection['host'],$connection['port']),(string)$connection['username'],(string)$connection['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$made=false;$db=null;
$clean=static function()use($server,$name,$safe,&$made,&$db):void{if(!$made)return;if($db!==null&&$db->connection()->inTransaction())$db->rollback();c6ok($safe($name),'Unsafe cleanup');$server->exec("DROP DATABASE `$name`");$made=false;};register_shutdown_function($clean);
try{c6ok(str_contains((string)$server->query('SELECT VERSION()')->fetchColumn(),'MariaDB'),'Real MariaDB required');c6ok($safe($name)&&$name!==$connection['database'],'Unsafe database');$server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$made=true;$config['default']='mysql';$config['connections']['mysql']['database']=$name;$db=new DatabaseManager($config);$pdo=$db->connection();$migrations=glob($root.'/database/migrations/*.sql')?:[];sort($migrations);foreach($migrations as$f)$pdo->exec(file_get_contents($f));$box=new Container();(new AppServiceProvider($box,[]))->register();$box->instance(DatabaseConnectionInterface::class,$db);
 $catalog=$box->make(PropertyCatalogService::class);$configuration=$box->make(UnitTypeConfigurationService::class);$geography=$box->make(GeographicLocationService::class);$development=$box->make(DevelopmentCatalogService::class);$projection=$box->make(PropertyFormProjectionService::class);$packages=[PropertyCategoriesSeedPackage::make($catalog),UnitTypesSeedPackage::make($catalog),MeasurementDefinitionsSeedPackage::make($catalog),AttributeDefinitionsSeedPackage::make($catalog),AttributeOptionsSeedPackage::make($catalog),UnitTypeConfigurationsSeedPackage::make($catalog,$configuration),EgyptGeographySeedPackage::make($geography)];$box->make(PropertyCatalogSeedRunner::class)->run($packages);
 $before=c6exec($pdo);$form=$projection->getCoreForm();c6eq(c6exec($pdo)-$before,4,'Core query count');c6eq(array_keys($form),['categories','unit_types','geography','development'],'Top-level structure');c6eq(count($form['categories']),6,'Six active Categories');c6eq(count($form['unit_types']),20,'Twenty active Unit Types');c6eq($form['geography']['countries'],[['id'=>$form['geography']['countries'][0]['id'],'code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر']],'Egypt only');c6eq($form['development']['developers'],[],'Empty Developers valid');
 $categoryCodes=array_column($form['categories'],'code','id');$expected=['APARTMENT'=>'RESIDENTIAL','VILLA'=>'RESIDENTIAL','COMMERCIAL_UNIT'=>'COMMERCIAL','RESIDENTIAL_LAND'=>'LAND'];foreach($form['unit_types']as$unit)c6ok(isset($categoryCodes[$unit['category_id']]),'Unit Category ID');foreach($form['unit_types']as$unit)if(isset($expected[$unit['code']]))c6eq($categoryCodes[$unit['category_id']],$expected[$unit['code']],$unit['code'].' category');c6ok(!isset($form['geography']['governorates'])&&!isset($form['development']['projects'])&&!isset($form['development']['phases']),'No eager descendants/projects/phases');
 $inactiveCategory=$catalog->createCategory(['code'=>'INACTIVE_CATEGORY','name_en'=>'Inactive Category','name_ar'=>'Inactive Category','provenance'=>'SYSTEM_ADMIN']);$catalog->deactivateCategory($inactiveCategory['id']);$inactiveUnit=$catalog->createUnitType(['code'=>'INACTIVE_UNIT','name_en'=>'Inactive Unit','name_ar'=>'Inactive Unit','property_category_id'=>$form['categories'][0]['id'],'provenance'=>'SYSTEM_ADMIN']);$catalog->deactivateUnitType($inactiveUnit['id']);$inactiveCountry=$geography->createLocation(['code'=>'INACTIVE_COUNTRY','name_en'=>'Inactive Country','name_ar'=>'Inactive Country','location_type'=>'COUNTRY','provenance'=>'SYSTEM_ADMIN']);$geography->deactivateLocation($inactiveCountry['id']);
 $activeDeveloper=$development->createDeveloper(['code'=>'ACTIVE_DEVELOPER','name_en'=>'Active Developer','name_ar'=>'Active Developer']);$inactiveDeveloper=$development->createDeveloper(['code'=>'INACTIVE_DEVELOPER','name_en'=>'Inactive Developer','name_ar'=>'Inactive Developer']);$development->deactivateDeveloper($inactiveDeveloper['id']);$after=$projection->getCoreForm();c6ok(!in_array('INACTIVE_CATEGORY',array_column($after['categories'],'code'),true),'Inactive Category excluded');c6ok(!in_array('INACTIVE_UNIT',array_column($after['unit_types'],'code'),true),'Inactive Unit excluded');c6eq(array_column($after['geography']['countries'],'code'),['EGYPT'],'Only active root Country; non-root Country is schema-forbidden');c6eq(array_column($after['development']['developers'],'code'),['ACTIVE_DEVELOPER'],'Active Developer only');c6eq(count(array_unique(array_column($after['categories'],'id'))),count($after['categories']),'No duplicate Categories');c6eq(count(array_unique(array_column($after['unit_types'],'id'))),count($after['unit_types']),'No duplicate Unit Types');echo "BF014.6C CoreFormProjectionService MariaDB acceptance: PASS\n";
}finally{$clean();}
