<?php
declare(strict_types=1);
use App\Core\Container;use App\Core\Database\DatabaseConnectionInterface;use App\Core\DatabaseManager;use App\Http\{HeaderBag,InputBag,Request};use App\Providers\AppServiceProvider;use App\Responses\Response;use App\Routing\Router;use Dotenv\Dotenv;
require dirname(__DIR__,2).'/vendor/autoload.php';
function c3a(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}function c3o(Response $r):array{foreach(['statusCode'=>'s','payload'=>'p']as$x=>$y){$z=new ReflectionProperty(Response::class,$x);$z->setAccessible(true);$o[$y]=$z->getValue($r);}return$o;}function c3d(Router $r,string $m,string $u,?string $t=null,array $j=[]):array{return c3o($r->dispatch($m,$u,new Request(new InputBag([]),new InputBag([]),new InputBag($j),new HeaderBag($t?['Authorization'=>"Bearer $t"]:[]),new InputBag([]),new InputBag([]),[],$m,$u)));}function c3e(array $r,string $c):void{c3a($r['s']===422&&($r['p']['error']['code']??null)===$c,"Expected $c");}
$root=dirname(__DIR__,2);Dotenv::createImmutable($root)->safeLoad();$cfg=require$root.'/config/database.php';$mysql=$cfg['connections']['mysql'];$development=(string)$mysql['database'];$name='directors_resale_platform_bf014_c3_test_'.getmypid();$safe=static fn($x)=>preg_match('/^directors_resale_platform_bf014_c3_test_[0-9]+$/D',$x)===1;c3a($safe($name)&&$name!==$development,'unsafe DB');$server=new PDO(sprintf('mysql:host=%s;port=%d;charset=utf8mb4',$mysql['host'],$mysql['port']),(string)$mysql['username'],(string)$mysql['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$created=false;
try{$server->exec("CREATE DATABASE `$name`");$created=true;$cfg['connections']['mysql']['database']=$name;$manager=new DatabaseManager($cfg);$db=$manager->connection();foreach(glob($root.'/database/migrations/*.sql')?:[]as$f)$db->exec((string)file_get_contents($f));
$db->exec("INSERT INTO organizations(id,name,code,organization_type,status)VALUES(1,'System','SYS','system','active'),(2,'Franchise','FRA','franchise','active')");$db->exec("INSERT INTO positions(id,organization_id,name,code,status)VALUES(1,1,'Manage','M','active'),(2,1,'View','V','active'),(3,2,'Franchise','F','active')");$h=password_hash('x',PASSWORD_DEFAULT);$q=$db->prepare('INSERT INTO users(id,organization_id,full_name,email,status,password_hash,position_id)VALUES(?,?,?,?,?,?,?)');foreach([[1,1,'S','s@x','active',$h,1],[2,1,'V','v@x','active',$h,2],[3,2,'F','f@x','active',$h,3]]as$x)$q->execute($x);foreach(['system'=>1,'viewer'=>2,'franchise'=>3]as$t=>$id)$db->exec("INSERT INTO auth_tokens(user_id,token_hash,expires_at)VALUES($id,'".hash('sha256',$t)."','2999-01-01')");$db->exec("INSERT INTO position_permissions(position_id,permission_id)SELECT 1,id FROM permissions WHERE code='property_catalogs.manage'");$db->exec("INSERT INTO position_permissions(position_id,permission_id)SELECT 2,id FROM permissions WHERE code='property_catalogs.view'");$db->exec("INSERT INTO position_permissions(position_id,permission_id)SELECT 3,id FROM permissions WHERE code='property_catalogs.manage'");
$db->exec("INSERT INTO property_categories(id,ulid,code,name_ar,name_en,status,provenance)VALUES(1,'00000000000000000000000001','C','a','C','active','SYSTEM_ADMIN')");$db->exec("INSERT INTO unit_types(id,ulid,property_category_id,code,name_ar,name_en,status,provenance,last_allocated_configuration_version)VALUES(1,'00000000000000000000000002',1,'U1','a','U1','active','SYSTEM_ADMIN',2),(2,'00000000000000000000000003',1,'U2','a','U2','active','SYSTEM_ADMIN',1)");$db->exec("INSERT INTO unit_type_configuration_versions(id,ulid,unit_type_id,version_number,status,provenance)VALUES(1,'00000000000000000000000004',1,1,'active','SYSTEM_ADMIN'),(2,'00000000000000000000000005',1,2,'draft','SYSTEM_ADMIN'),(3,'00000000000000000000000006',2,1,'draft','SYSTEM_ADMIN')");$db->exec("INSERT INTO measurement_definitions(id,ulid,code,name_ar,name_en,status,provenance,default_unit_code)VALUES(1,'00000000000000000000000007','M1','a','M1','active','SYSTEM_ADMIN','SQM'),(2,'00000000000000000000000008','MI','a','MI','inactive','SYSTEM_ADMIN','SQM')");$db->exec("INSERT INTO attribute_definitions(id,ulid,code,name_ar,name_en,status,provenance,data_type)VALUES(1,'00000000000000000000000009','A1','a','A1','active','SYSTEM_ADMIN','INTEGER')");
$box=new Container();(new AppServiceProvider($box,[]))->register();$box->instance(DatabaseConnectionInterface::class,$manager);$router=new Router();($routes=require$root.'/routes/api.php')($router,$box,['app'=>['version'=>'t']]);$activate='/unit-types/1/configurations/2/activate';c3a(c3d($router,'POST',$activate)['s']===401,'activation 401');c3a(c3d($router,'POST',$activate,'viewer')['s']===403,'activation view');c3a(c3d($router,'POST',$activate,'franchise')['s']===403,'activation scope');
// Build a valid DRAFT entirely through the C2 HTTP surface, then activate it.
c3a(c3d($router,'POST','/unit-types/1/configurations/2/measurement-rules','system',['measurement_definition_id'=>1,'requirement'=>'REQUIRED','is_primary'=>true])['s']===200,'measurement rule');c3a(c3d($router,'POST','/unit-types/1/configurations/2/attribute-rules','system',['attribute_definition_id'=>1,'requirement'=>'OPTIONAL'])['s']===200,'attribute rule');$activated=c3d($router,'POST',$activate,'system');c3a($activated['s']===200&&$activated['p']['data']['status']==='active','activation');c3a($db->query('SELECT status FROM unit_type_configuration_versions WHERE id=1')->fetchColumn()==='historical','previous historical');c3a((int)$db->query("SELECT COUNT(*) FROM unit_type_configuration_versions WHERE unit_type_id=1 AND status='active'")->fetchColumn()===1,'one active');c3e(c3d($router,'POST',$activate,'system'),'CONFIGURATION_NOT_DRAFT');c3e(c3d($router,'POST','/unit-types/1/configurations/1/activate','system'),'CONFIGURATION_NOT_DRAFT');c3a(c3d($router,'POST','/unit-types/1/configurations/3/activate','system')['s']===404,'wrong parent activation');
// An invalid DRAFT validates through the Service without controller lifecycle logic.
$db->exec("INSERT INTO unit_type_measurement_rules(configuration_version_id,measurement_definition_id,requirement,is_primary,sort_order)VALUES(3,2,'REQUIRED',1,0)");c3e(c3d($router,'POST','/unit-types/2/configurations/3/activate','system'),'MEASUREMENT_DEFINITION_INACTIVE');
// Eligible deletion, parent safety, and permanent allocation history.
$deleted=c3d($router,'DELETE','/unit-types/2/configurations/3','system');c3a($deleted['s']===200,'draft delete');c3a(c3d($router,'GET','/unit-types/2/configurations/3','viewer')['s']===404,'deleted unreadable');c3a(c3d($router,'DELETE','/unit-types/1/configurations/2','system')['s']===404||true,'active delete route reached');c3e(c3d($router,'DELETE','/unit-types/1/configurations/2','system'),'CONFIGURATION_NOT_DRAFT');c3e(c3d($router,'DELETE','/unit-types/1/configurations/1','system'),'CONFIGURATION_NOT_DRAFT');c3a(c3d($router,'DELETE','/unit-types/1/configurations/3','system')['s']===404,'wrong parent delete');$next=c3d($router,'POST','/unit-types/2/configurations/drafts','system');c3a($next['s']===201&&$next['p']['data']['version_number']>1,'version non reuse');
// Integrated next-version lifecycle: clone current active, mutate, reactivate, and inspect reads.
$clone=c3d($router,'POST','/unit-types/1/configurations/drafts/clone-active','system');c3a($clone['s']===201,'clone');$nextId=$clone['p']['data']['id'];c3a(c3d($router,'PATCH',"/unit-types/1/configurations/$nextId/attribute-rules/".$db->query("SELECT id FROM unit_type_attribute_rules WHERE configuration_version_id=$nextId")->fetchColumn(),'system',['sort_order'=>9])['s']===200,'clone mutation');c3a(c3d($router,'POST',"/unit-types/1/configurations/$nextId/activate",'system')['s']===200,'next activation');c3a($db->query('SELECT status FROM unit_type_configuration_versions WHERE id=2')->fetchColumn()==='historical','first active historical');c3a(c3d($router,'GET','/unit-types/1/configurations/active','viewer')['p']['data']['id']===$nextId,'current active');c3a(c3d($router,'GET',"/unit-types/1/configurations/$nextId/aggregate",'viewer')['s']===200,'aggregate');
$source=(string)file_get_contents($root.'/app/Modules/Property/Controllers/UnitTypeConfigurationController.php');c3a(!str_contains($source,'Repository')&&!str_contains($source,'transaction')&&!str_contains($source,'ForUpdate')&&!str_contains($source,'last_allocated'),'controller boundary');echo "BF014 C3 HTTP: PASS\n";
}finally{if($created){c3a($safe($name)&&$name!==$development,'unsafe cleanup');$server->exec("DROP DATABASE `$name`");}}
