<?php
declare(strict_types=1);

use App\Core\Container;
use App\Core\Database\DatabaseConnectionInterface;
use App\Core\DatabaseManager;
use App\Modules\Property\Seeds\{PropertyCategoriesSeedPackage,UnitTypesSeedPackage,MeasurementDefinitionsSeedPackage,AttributeDefinitionsSeedPackage,AttributeOptionsSeedPackage,UnitTypeConfigurationsSeedPackage};
use App\Modules\Property\Services\{PropertyCatalogSeedRunner,PropertyCatalogService,UnitTypeConfigurationService};
use App\Providers\AppServiceProvider;

require dirname(__DIR__, 2) . '/vendor/autoload.php';
function ccheck(bool $condition, string $message): void { if (!$condition) { throw new RuntimeException($message); } }
function ccollision(callable $call): void { try { $call(); } catch (RuntimeException $e) { ccheck($e->getMessage() === 'SEED_PACKAGE_COLLISION', 'Unexpected collision: '.$e->getMessage()); return; } throw new RuntimeException('Expected SEED_PACKAGE_COLLISION'); }
$root=dirname(__DIR__,2); Dotenv\Dotenv::createImmutable($root)->safeLoad(); $config=require $root.'/config/database.php'; $c=$config['connections']['mysql']; $name='directors_resale_platform_c_seed_test_'.getmypid();
ccheck(preg_match('/^directors_resale_platform_c_seed_test_[0-9]+$/D',$name)===1 && $name!==$c['database'],'Unsafe database');
$server=new PDO(sprintf('mysql:host=%s;port=%d;charset=utf8mb4',$c['host'],$c['port']),$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $created=false;$db=null;
try {
    ccheck(str_contains((string)$server->query('SELECT VERSION()')->fetchColumn(),'MariaDB'),'Real MariaDB required'); $server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$created=true;
    $config['connections']['mysql']['database']=$name;$db=new DatabaseManager($config);$pdo=$db->connection();$files=glob($root.'/database/migrations/*.sql');sort($files);foreach($files as $file){$pdo->exec(file_get_contents($file));}
    $box=new Container();(new AppServiceProvider($box,[]))->register();$box->instance(DatabaseConnectionInterface::class,$db);$catalog=$box->make(PropertyCatalogService::class);$configs=$box->make(UnitTypeConfigurationService::class);$runner=$box->make(PropertyCatalogSeedRunner::class);
    $one=PropertyCategoriesSeedPackage::make($catalog);$two=UnitTypesSeedPackage::make($catalog);$three=MeasurementDefinitionsSeedPackage::make($catalog);$four=AttributeDefinitionsSeedPackage::make($catalog);$five=AttributeOptionsSeedPackage::make($catalog);$six=UnitTypeConfigurationsSeedPackage::make($catalog,$configs);$packages=[$six,$three,$one,$five,$two,$four];$matrix=UnitTypeConfigurationsSeedPackage::matrix();
    ccheck(count($matrix)===20 && count(array_unique(array_keys($matrix)))===20,'Matrix incomplete or ambiguous'); ccheck(preg_match('/^[0-9a-f]{64}$/D',$six->checksum())===1 && $six->checksum()===UnitTypeConfigurationsSeedPackage::make($catalog,$configs)->checksum(),'Checksum determinism');
    $applied=[];foreach([$one,$two,$three,$four,$five,$six] as $p){$applied[]='APPLY '.$p->key;$applied[]='DONE '.$p->key;}$skipped=array_map(fn($p)=>'SKIP '.$p->key,[$one,$two,$three,$four,$five,$six]);
    $actual=function(array $aggregate):array{return ['measurements'=>array_map(fn($r)=>[$r['definition']['code'],$r['rule']['requirement'],(bool)$r['rule']['is_primary']],$aggregate['measurement_rules']),'attributes'=>array_map(fn($r)=>[$r['definition']['code'],$r['rule']['requirement']],$aggregate['attribute_rules'])];};
    $verify=function()use($catalog,$configs,$matrix,$actual,$pdo,$one,$two,$three,$four,$five,$six):void{$units=array_column($catalog->listUnitTypes(['limit'=>100]),null,'code');ccheck(count($units)===20,'Twenty unit types');foreach($matrix as $code=>$expected){$rows=$configs->listConfigurations($units[$code]['id']);ccheck(count($rows)===1,'One configuration '.$code);$row=$rows[0];ccheck($row['version_number']===1&&$row['status']==='active'&&$row['provenance']==='SYSTEM_SEED','Config lifecycle '.$code);ccheck($actual($configs->aggregate($row['id']))===$expected,'Exact matrix '.$code);if(str_ends_with($code,'_LAND')){ccheck($expected['measurements']===[['PLOT_AREA','REQUIRED',true]]&&$expected['attributes']===[],'Land matrix '.$code);}}ccheck((int)$pdo->query("SELECT COUNT(*) FROM unit_type_configuration_versions WHERE status='draft'")->fetchColumn()===0&&(int)$pdo->query("SELECT COUNT(*) FROM unit_type_configuration_versions WHERE status='historical'")->fetchColumn()===0,'Fresh draft/historical');ccheck(array_column($pdo->query('SELECT seed_key FROM property_catalog_seed_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC),'seed_key')===[$one->key,$two->key,$three->key,$four->key,$five->key,$six->key],'Ledger order');};
    ccheck($runner->run($packages)===$applied,'Fresh package order');$verify();$before=$pdo->query('SELECT * FROM unit_type_configuration_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);$allocator=$pdo->query('SELECT code,last_allocated_configuration_version FROM unit_types ORDER BY code')->fetchAll(PDO::FETCH_ASSOC);ccheck($runner->run($packages)===$skipped&&$pdo->query('SELECT * FROM unit_type_configuration_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$before&&$pdo->query('SELECT code,last_allocated_configuration_version FROM unit_types ORDER BY code')->fetchAll(PDO::FETCH_ASSOC)===$allocator,'Rerun mutation/allocation');
    $measurement=$catalog->listMeasurementDefinitions()[0];$catalog->updateMeasurementDefinition($measurement['id'],['name_en'=>'Admin edit']);$before=$pdo->query('SELECT * FROM unit_type_configuration_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);ccheck($runner->run($packages)===$skipped&&$pdo->query('SELECT * FROM unit_type_configuration_versions ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)===$before,'Admin modification/history');
    $pdo->exec('DELETE FROM property_catalog_seed_versions WHERE seed_key='.$pdo->quote($six->key));ccheck($runner->run([$six])===['APPLY '.$six->key,'DONE '.$six->key],'Compatible seeded recovery');$verify();
    $catalog->updateMeasurementDefinition($measurement['id'], ['name_en'=>$measurement['code']]);
    $pdo->exec('DELETE FROM unit_type_attribute_rules');$pdo->exec('DELETE FROM unit_type_measurement_rules');
    $pdo->exec('DELETE FROM property_catalog_seed_versions');$pdo->exec('DELETE FROM unit_type_configuration_versions');$pdo->exec('UPDATE unit_types SET last_allocated_configuration_version=0');$runner->run([$one,$two,$three,$four,$five]);$units=array_column($catalog->listUnitTypes(['limit'=>100]),null,'code');$measurements=array_column($catalog->listMeasurementDefinitions(['limit'=>100]),null,'code');$conflict=$configs->createBlankDraft($units['WAREHOUSE']['id'],null,'SYSTEM_ADMIN');$configs->addMeasurementRule($units['WAREHOUSE']['id'],$conflict['id'],['measurement_definition_id'=>$measurements['BUILT_UP_AREA']['id'],'requirement'=>'REQUIRED','is_primary'=>true]);$configs->activate($units['WAREHOUSE']['id'],$conflict['id']);$before=$pdo->query('SELECT code,last_allocated_configuration_version FROM unit_types ORDER BY code')->fetchAll(PDO::FETCH_ASSOC);ccollision(fn()=>$runner->run([$six]));ccheck((int)$pdo->query("SELECT COUNT(*) FROM property_catalog_seed_versions WHERE seed_key='006-unit-type-configurations'")->fetchColumn()===0,'Failed 006 ledger');ccheck((int)$pdo->query('SELECT COUNT(*) FROM unit_type_configuration_versions')->fetchColumn()===1,'Partial configuration rollback');ccheck($pdo->query('SELECT code,last_allocated_configuration_version FROM unit_types ORDER BY code')->fetchAll(PDO::FETCH_ASSOC)===$before,'Allocator rollback');ccheck((int)$pdo->query('SELECT COUNT(*) FROM property_catalog_seed_versions')->fetchColumn()===5,'Earlier ledger persistence');
    $pdo->exec('DELETE FROM unit_type_attribute_rules');$pdo->exec('DELETE FROM unit_type_measurement_rules');$pdo->exec('DELETE FROM unit_type_configuration_versions');$pdo->exec('UPDATE unit_types SET last_allocated_configuration_version=0');$conflict=$configs->createBlankDraft($units['WAREHOUSE']['id'],null,'SYSTEM_SEED');$configs->addMeasurementRule($units['WAREHOUSE']['id'],$conflict['id'],['measurement_definition_id'=>$measurements['BUILT_UP_AREA']['id'],'requirement'=>'REQUIRED','is_primary'=>true]);$configs->activate($units['WAREHOUSE']['id'],$conflict['id']);ccollision(fn()=>$runner->run([$six]));ccheck((int)$pdo->query('SELECT COUNT(*) FROM unit_type_configuration_versions')->fetchColumn()===1,'Incompatible seeded state overwritten');
    $pdo->exec('DELETE FROM unit_type_measurement_rules');$pdo->exec('DELETE FROM unit_type_configuration_versions');$pdo->exec('UPDATE unit_types SET last_allocated_configuration_version=0');$pdo->exec('DELETE FROM property_catalog_seed_versions');
    $cli=function()use($root,$name,$c):array{$env=['DB_CONNECTION'=>'mysql','DB_DATABASE'=>$name,'DB_HOST'=>$c['host'],'DB_PORT'=>$c['port'],'DB_USERNAME'=>$c['username'],'DB_PASSWORD'=>$c['password']];$code='$_ENV = array_replace($_ENV, '.var_export($env,true).'); require '.var_export($root.'/bin/seed-property-catalog.php',true).';';$process=proc_open([PHP_BINARY,'-r',$code],[1=>['pipe','w'],2=>['pipe','w']],$pipes,$root);ccheck(is_resource($process),'CLI unavailable');$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);ccheck(proc_close($process)===0&&$err==='','CLI failure');return preg_split('/\R/',trim($out));};ccheck($cli()===$applied,'CLI first run');ccheck($cli()===$skipped,'CLI second run');
    echo "BF014 C production configuration package + isolated CLI MariaDB acceptance: PASS\n";
} finally {if($db!==null&&$db->connection()->inTransaction()){$db->rollback();}if($created){$server->exec("DROP DATABASE `$name`");}}
