<?php
declare(strict_types=1);
use App\Core\Container;use App\Core\Database\DatabaseConnectionInterface;use App\Core\DatabaseManager;use App\Exceptions\ValidationException;use App\Modules\Property\Repositories\PropertyCatalogRepository;use App\Modules\Property\Repositories\UnitTypeConfigurationRepository;use App\Modules\Property\Services\PropertyCatalogService;use App\Modules\Property\Services\UnitTypeConfigurationService;use App\Providers\AppServiceProvider;use Dotenv\Dotenv;
require dirname(__DIR__,2).'/vendor/autoload.php';
function c5dAssert(bool $ok,string $m):void{if(!$ok)throw new RuntimeException($m);}
function c5dWorker(string $root,string $name,int $unit,int $draft):array{$cfg=require $root.'/config/database.php';$cfg['connections']['mysql']['database']=$name;$db=new DatabaseManager($cfg);$db->connection()->exec('SET SESSION innodb_lock_wait_timeout = 5');$c=new Container();(new AppServiceProvider($c,[]))->register();$c->instance(DatabaseConnectionInterface::class,$db);try{$c->make(UnitTypeConfigurationService::class)->activate($unit,$draft);return['result'=>'ok'];}catch(ValidationException $e){return['result'=>'validation','code'=>(string)array_key_first($e->errors())];}catch(Throwable $e){return['result'=>'error','error'=>$e::class.': '.$e->getMessage()];}}
/** @param array<int,resource> $pipes @return resource */
function c5dStart(string $db,int $unit,int $draft,array &$pipes):mixed{$cmd=escapeshellarg(PHP_BINARY).' '.escapeshellarg(__FILE__).' --c5d-worker '.escapeshellarg($db)." $unit $draft";$p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__,2));if(!is_resource($p))throw new RuntimeException('Worker launch failed.');stream_set_blocking($pipes[1],false);stream_set_blocking($pipes[2],false);return$p;}
/** @param resource $p @param array<int,resource> $pipes */
function c5dFinish(mixed $p,array $pipes):array{$deadline=microtime(true)+6;while(proc_get_status($p)['running']){if(microtime(true)>=$deadline){proc_terminate($p);throw new RuntimeException('Worker timeout.');}usleep(20_000);}$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($p);$r=json_decode(trim($out),true);if($exit!==0||!is_array($r))throw new RuntimeException('Worker failed: '.trim($err.' '.$out));return$r;}
$root=dirname(__DIR__,2);Dotenv::createImmutable($root)->safeLoad();if(($argv[1]??null)==='--c5d-worker'){$r=c5dWorker($root,(string)$argv[2],(int)$argv[3],(int)$argv[4]);echo json_encode($r,JSON_THROW_ON_ERROR);exit($r['result']==='error'?1:0);}
$cfg=require $root.'/config/database.php';$co=$cfg['connections']['mysql'];$name='directors_resale_platform_c5d_test_'.getmypid();c5dAssert(preg_match('/^directors_resale_platform_c5d_test_[0-9]+$/D',$name)===1&&$name!==$co['database'],'Unsafe database');$server=new PDO(sprintf('mysql:host=%s;port=%d;charset=utf8mb4',$co['host'],$co['port']),$co['username'],$co['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$created=false;$db=null;$a=$b=null;$ap=$bp=[];
try{$server->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$created=true;$cfg['connections']['mysql']['database']=$name;$db=new DatabaseManager($cfg);$pdo=$db->connection();$files=glob($root.'/database/migrations/*.sql')?:[];sort($files);foreach($files as $f)$pdo->exec(file_get_contents($f));$c=new Container();(new AppServiceProvider($c,[]))->register();$c->instance(DatabaseConnectionInterface::class,$db);$catalog=$c->make(PropertyCatalogService::class);$service=$c->make(UnitTypeConfigurationService::class);$units=$c->make(PropertyCatalogRepository::class);$configs=$c->make(UnitTypeConfigurationRepository::class);
$cat=$catalog->createCategory(['code'=>'C5D','name_ar'=>'C5D','name_en'=>'C5D']);$unit=$catalog->createUnitType(['property_category_id'=>$cat['id'],'code'=>'C5D','name_ar'=>'C5D','name_en'=>'C5D']);$old=$service->createBlankDraft($unit['id']);$service->activate($unit['id'],$old['id']);$draft=$service->cloneActiveDraft($unit['id']);$counter=$units->findUnitTypeById($unit['id'])['last_allocated_configuration_version'];$countBefore=count($configs->listConfigurationsForUnitType($unit['id']));$lock='bf014_c5d_activate_'.getmypid();$pdo->exec("CREATE TRIGGER c5d_pause BEFORE UPDATE ON unit_type_configuration_versions FOR EACH ROW BEGIN IF NEW.id = {$draft['id']} AND NEW.status = 'active' THEN DO GET_LOCK('$lock',0);DO SLEEP(2);END IF;END");
$a=c5dStart($name,$unit['id'],$draft['id'],$ap);$deadline=microtime(true)+3;$owner=null;do{$s=$server->prepare('SELECT IS_USED_LOCK(?)');$s->execute([$lock]);$owner=$s->fetchColumn();if($owner!==null)break;usleep(20_000);}while(microtime(true)<$deadline);c5dAssert($owner!==null,'Activation did not reach guarded target update');$startedB=microtime(true);$b=c5dStart($name,$unit['id'],$draft['id'],$bp);$ra=c5dFinish($a,$ap);$a=null;$rb=c5dFinish($b,$bp);$b=null;$wait=microtime(true)-$startedB;c5dAssert($ra['result']==='ok','A activation');c5dAssert($rb['result']==='validation'&&($rb['code']??null)==='CONFIGURATION_NOT_DRAFT','B activation');c5dAssert($wait>=.5,'B did not contend');
c5dAssert($configs->findConfigurationById($draft['id'])['status']==='active','Target not active');c5dAssert($configs->findConfigurationById($old['id'])['status']==='historical','Old active not historical');c5dAssert(count($configs->listConfigurationsForUnitType($unit['id'],['status'=>'active']))===1&&$configs->findDraftConfigurationForUnitType($unit['id'])===null,'Final lifecycle counts');c5dAssert($configs->listMeasurementRules($draft['id'])===[]&&$configs->listAttributeRules($draft['id'])===[],'Rules changed');c5dAssert($units->findUnitTypeById($unit['id'])['last_allocated_configuration_version']===$counter,'Counter changed');c5dAssert(count($configs->listConfigurationsForUnitType($unit['id']))===$countBefore,'Extra configuration created');echo"C5d real competing activation: PASS; B_wait_seconds=".number_format($wait,3)."\n";
}finally{foreach([[$a,$ap],[$b,$bp]]as[$p,$pipes])if($p!==null){proc_terminate($p);foreach($pipes as$pipe)fclose($pipe);proc_close($p);}if($db!==null&&$db->connection()->inTransaction())$db->rollback();if($created)$server->exec("DROP DATABASE `$name`");}
