<?php
declare(strict_types=1);
namespace App\Modules\Property\Controllers;
use App\Exceptions\ValidationException;use App\Http\Request;use App\Modules\Property\Services\DevelopmentCatalogService;use App\Responses\Response;
final class DevelopmentCatalogController{
 public function __construct(private DevelopmentCatalogService $service){}
 public function developers(Request $r):Response{return $this->list(fn($o)=>$this->service->listDevelopers($o),$r);}
 public function developer(Request $r,int|string $id):Response{return $this->item(fn()=> $this->service->findDeveloper($id));}
 public function projects(Request $r):Response{return $this->list(fn($o)=>$this->service->listProjects($o),$r,['developer_id','geographic_location_id']);}
 public function project(Request $r,int|string $id):Response{return $this->item(fn()=> $this->service->findProject($id));}
 public function phases(Request $r):Response{try{$id=$r->query('project_id');if($id===null)throw new ValidationException(['project_id'=>'Required.']);return Response::success('Project Phases retrieved.',$this->service->listProjectPhases($id,$this->options($r)));}catch(ValidationException $e){return $this->error($e);}}
 public function phase(Request $r,int|string $id):Response{return $this->item(fn()=> $this->service->findProjectPhase($id));}
 public function createDeveloper(Request $r):Response{return $this->create($r,fn($d,$a)=>$this->service->createDeveloper($d,$a));} public function updateDeveloper(Request $r,int|string $id):Response{return $this->update($r,$id,fn()=>$this->service->findDeveloper($id),fn($d,$a)=>$this->service->updateDeveloper($id,$d,$a));}
 public function createProject(Request $r):Response{return $this->create($r,fn($d,$a)=>$this->service->createProject($d,$a));} public function updateProject(Request $r,int|string $id):Response{return $this->update($r,$id,fn()=>$this->service->findProject($id),fn($d,$a)=>$this->service->updateProject($id,$d,$a));}
 public function createPhase(Request $r):Response{try{$d=$r->all();$p=$d['project_id']??null;unset($d['project_id']);return Response::success('Project Phase created.',$this->service->createProjectPhase($p,$d,$this->actor($r)),[],201);}catch(ValidationException $e){return $this->error($e);}}
 public function updatePhase(Request $r,int|string $id):Response{return $this->phaseOp($r,$id,fn($p,$d,$a)=>$this->service->updateProjectPhase($p,$id,$d,$a),'Project Phase updated.');}
 public function deactivateDeveloper(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findDeveloper($id),fn()=> $this->service->deactivateDeveloper($id,$this->actor($r)));} public function reactivateDeveloper(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findDeveloper($id),fn()=> $this->service->reactivateDeveloper($id,$this->actor($r)));} public function deleteDeveloper(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findDeveloper($id),fn()=> $this->service->deleteDeveloper($id));}
 public function deactivateProject(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findProject($id),fn()=> $this->service->deactivateProject($id,$this->actor($r)));} public function reactivateProject(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findProject($id),fn()=> $this->service->reactivateProject($id,$this->actor($r)));} public function deleteProject(Request $r,int|string $id):Response{return $this->action($r,fn()=> $this->service->findProject($id),fn()=> $this->service->deleteProject($id));}
 public function deactivatePhase(Request $r,int|string $id):Response{return $this->phaseOp($r,$id,fn($p)=>$this->service->deactivateProjectPhase($p,$id,$this->actor($r)),'Project Phase deactivated.');}public function reactivatePhase(Request $r,int|string $id):Response{return $this->phaseOp($r,$id,fn($p)=>$this->service->reactivateProjectPhase($p,$id,$this->actor($r)),'Project Phase reactivated.');}public function deletePhase(Request $r,int|string $id):Response{return $this->phaseOp($r,$id,fn($p)=>$this->service->deleteProjectPhase($p,$id),'Project Phase deleted.');}
 private function list(callable $op,Request $r,array $extra=[]):Response{try{return Response::success('Development Catalog retrieved.',$op($this->options($r,$extra)));}catch(ValidationException $e){return $this->error($e);}}private function item(callable $op):Response{try{$x=$op();return $x===null?$this->missing():Response::success('Development Catalog retrieved.',$x);}catch(ValidationException $e){return $this->error($e);}}private function create(Request $r,callable $op):Response{try{return Response::success('Development Catalog created.',$op($r->all(),$this->actor($r)),[],201);}catch(ValidationException $e){return $this->error($e);}}private function update(Request $r,int|string $id,callable $find,callable $op):Response{try{if($find()===null)return $this->missing();$x=$op($r->all(),$this->actor($r));return $x===null?$this->missing():Response::success('Development Catalog updated.',$x);}catch(ValidationException $e){return $this->error($e);}}
 private function action(Request $r,callable $find,callable $op):Response{try{if($find()===null)return $this->missing();$x=$op();return is_bool($x)?Response::success('Development Catalog changed.'):Response::success('Development Catalog changed.',$x);}catch(ValidationException $e){return $this->error($e);}}private function phaseOp(Request $r,int|string $id,callable $op,string $m):Response{try{$x=$this->service->findProjectPhase($id);if($x===null)return $this->missing();$v=$op($x['project_id'],$r->all(),$this->actor($r));return is_bool($v)?Response::success($m):Response::success($m,$v);}catch(ValidationException $e){return $this->error($e);}}
 private function options(Request $r,array $extra=[]):array{$o=[];foreach(array_merge(['status','search','limit','offset'],$extra)as$k)if(($v=$r->query($k))!==null)$o[$k]=in_array($k,['limit','offset','developer_id','geographic_location_id','project_id'],true)?(int)$v:$v;return $o;}private function actor(Request $r):int{return(int)((array)$r->attribute('auth.user'))['id'];}private function missing():Response{return Response::error('not_found','Development Catalog item not found.',404);}private function error(ValidationException $e):Response{$x=$e->errors();return Response::json(['success'=>false,'error'=>['code'=>(string)array_key_first($x),'message'=>'The Development Catalog request is invalid.','fields'=>$x]],422);}
}
