<?php
declare(strict_types=1);
namespace App\Modules\Property\Controllers;
use App\Exceptions\ValidationException; use App\Http\Request; use App\Modules\Property\Services\UnitTypeConfigurationService; use App\Modules\Property\Services\PropertyCatalogService; use App\Responses\Response;
final class UnitTypeConfigurationController {
 public function __construct(private UnitTypeConfigurationService $configs,private PropertyCatalogService $catalogs){}
 public function index(Request $r,int|string $unit):Response{return $this->read(fn()=> $this->configs->listConfigurations($unit),'Configurations');}
 public function active(Request $r,int|string $unit):Response{return $this->read(fn()=> $this->configs->findActive($unit),'Active Configuration');}
 public function draft(Request $r,int|string $unit):Response{return $this->read(fn()=> $this->configs->findDraft($unit),'Draft Configuration');}
 public function show(Request $r,int|string $unit,int|string $id):Response{return $this->configuration($unit,$id,fn()=> $this->configs->findConfiguration($id),'Configuration');}
 public function aggregate(Request $r,int|string $unit,int|string $id):Response{return $this->configuration($unit,$id,fn()=> $this->configs->aggregate($id),'Configuration Aggregate');}
 public function createDraft(Request $r,int|string $unit):Response{return $this->mutate($unit,fn()=> $this->configs->createBlankDraft($unit,$this->actor($r)),'Draft created.');}
 public function cloneActive(Request $r,int|string $unit):Response{return $this->mutate($unit,fn()=> $this->configs->cloneActiveDraft($unit,$this->actor($r)),'Draft cloned.');}
 public function activate(Request $r,int|string $unit,int|string $configuration):Response{return $this->lifecycle($unit,$configuration,fn()=> $this->configs->activate($unit,$configuration,$this->actor($r)),'Configuration activated.');}
 public function deleteDraft(Request $r,int|string $unit,int|string $configuration):Response{return $this->lifecycle($unit,$configuration,fn()=> $this->configs->deleteDraft($unit,$configuration),'Draft deleted.');}
 public function addMeasurementRule(Request $r,int|string $unit,int|string $configuration):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->addMeasurementRule($unit,$configuration,$d,$this->actor($r)),'Measurement Rule added.',['measurement_definition_id','requirement']);}
 public function updateMeasurementRule(Request $r,int|string $unit,int|string $configuration,int|string $rule):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->updateMeasurementRule($unit,$configuration,$rule,$d,$this->actor($r)),'Measurement Rule updated.');}
 public function removeMeasurementRule(Request $r,int|string $unit,int|string $configuration,int|string $rule):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->removeMeasurementRule($unit,$configuration,$rule),'Measurement Rule removed.');}
 public function addAttributeRule(Request $r,int|string $unit,int|string $configuration):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->addAttributeRule($unit,$configuration,$d,$this->actor($r)),'Attribute Rule added.',['attribute_definition_id','requirement']);}
 public function updateAttributeRule(Request $r,int|string $unit,int|string $configuration,int|string $rule):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->updateAttributeRule($unit,$configuration,$rule,$d,$this->actor($r)),'Attribute Rule updated.');}
 public function removeAttributeRule(Request $r,int|string $unit,int|string $configuration,int|string $rule):Response{return $this->rule($r,$unit,$configuration,fn($d)=>$this->configs->removeAttributeRule($unit,$configuration,$rule),'Attribute Rule removed.');}
 private function configuration(int|string $unit,int|string $id,callable $op,string $name):Response{try{$parent=$this->configs->findConfiguration($id);if($parent===null||(int)$parent['unit_type_id']!==(int)$unit)return $this->missing($name);$record=$op();return $record===null?$this->missing($name):Response::success("$name retrieved.",$record);}catch(ValidationException $e){return $this->error($e);}}
 private function read(callable $op,string $name):Response{try{$record=$op();return $record===null?$this->missing($name):Response::success("$name retrieved.",$record);}catch(ValidationException $e){return $this->error($e);}}
 private function mutate(int|string $unit,callable $op,string $message):Response{try{if($this->catalogs->findUnitType($unit)===null)return $this->missing('Unit Type');return Response::success($message,$op(),[],201);}catch(ValidationException $e){return $this->error($e);}}
 private function lifecycle(int|string $unit,int|string $configuration,callable $op,string $message):Response{try{$record=$this->configs->findConfiguration($configuration);if($record===null||(int)$record['unit_type_id']!==(int)$unit)return $this->missing('Configuration');$result=$op();return is_bool($result)?Response::success($message):Response::success($message,$result);}catch(ValidationException $e){return $this->error($e);}}
 private function rule(Request $r,int|string $unit,int|string $configuration,callable $op,string $message,array $required=[]):Response{try{$record=$this->configs->findConfiguration($configuration);if($record===null||(int)$record['unit_type_id']!==(int)$unit)return $this->missing('Configuration');$data=$r->all();foreach($required as$key)if(!array_key_exists($key,$data))throw new ValidationException([$key=>'Required.']);$result=$op($data);return is_bool($result)?Response::success($message):($result===null?$this->missing('Rule'):Response::success($message,$result));}catch(ValidationException $e){return $this->error($e);}}
 private function actor(Request $r):int{return(int)((array)$r->attribute('auth.user'))['id'];} private function missing(string $n):Response{return Response::error('not_found',"$n not found.",404);} private function error(ValidationException $e):Response{$x=$e->errors();return Response::json(['success'=>false,'error'=>['code'=>(string)array_key_first($x),'message'=>'The Configuration request is invalid.','fields'=>$x]],422);}
}
