<?php
declare(strict_types=1);
namespace App\Modules\Property\Seeds;
use App\Modules\Property\Services\GeographicLocationService;
use App\Modules\Property\Services\PropertyCatalogSeedPackage;
final class EgyptGeographySeedPackage {
 public static function make(GeographicLocationService $locations):PropertyCatalogSeedPackage{$rows=self::rows();return new PropertyCatalogSeedPackage('007-egypt-geography',7,json_encode($rows,JSON_THROW_ON_ERROR),function()use($locations,$rows):void{$all=[];foreach($locations->listLocations(['limit'=>100])as$r)$all[$r['code']]=$r;$egypt=$all['EGYPT']??null;if($egypt){if(!self::matches($egypt,$rows[0],null))throw new \RuntimeException('SEED_PACKAGE_COLLISION');}else{$egypt=$locations->createLocation(['code'=>'EGYPT','name_en'=>'Egypt','name_ar'=>'مصر','location_type'=>'COUNTRY','sort_order'=>1,'provenance'=>'SYSTEM_SEED']);}$all['EGYPT']=$egypt;foreach(array_slice($rows,1)as$row){$found=$all[$row[0]]??null;if($found){if(!self::matches($found,$row,$egypt['id']))throw new \RuntimeException('SEED_PACKAGE_COLLISION');continue;}$locations->createLocation(['code'=>$row[0],'name_en'=>$row[1],'name_ar'=>$row[2],'location_type'=>'GOVERNORATE','parent_id'=>$egypt['id'],'sort_order'=>$row[3],'provenance'=>'SYSTEM_SEED']);}});}
 /** @return list<array{string,string,string,int}> */ public static function rows():array{return [
 ['EGYPT','Egypt','مصر',1],['CAIRO','Cairo','القاهرة',1],['ALEXANDRIA','Alexandria','الإسكندرية',2],['GIZA','Giza','الجيزة',3],['QALYUBIA','Qalyubia','القليوبية',4],['DAKAHLIA','Dakahlia','الدقهلية',5],['SHARQIA','Sharqia','الشرقية',6],['GHARBIA','Gharbia','الغربية',7],['MONUFIA','Monufia','المنوفية',8],['BEHEIRA','Beheira','البحيرة',9],['KAFR_EL_SHEIKH','Kafr El Sheikh','كفر الشيخ',10],['DAMIETTA','Damietta','دمياط',11],['PORT_SAID','Port Said','بورسعيد',12],['ISMAILIA','Ismailia','الإسماعيلية',13],['SUEZ','Suez','السويس',14],['NORTH_SINAI','North Sinai','شمال سيناء',15],['SOUTH_SINAI','South Sinai','جنوب سيناء',16],['FAYOUM','Fayoum','الفيوم',17],['BENI_SUEF','Beni Suef','بني سويف',18],['MINYA','Minya','المنيا',19],['ASSIUT','Assiut','أسيوط',20],['SOHAG','Sohag','سوهاج',21],['QENA','Qena','قنا',22],['LUXOR','Luxor','الأقصر',23],['ASWAN','Aswan','أسوان',24],['RED_SEA','Red Sea','البحر الأحمر',25],['NEW_VALLEY','New Valley','الوادي الجديد',26],['MATROUH','Matrouh','مطروح',27]];}
 private static function matches(array $found,array $row,?int $parent):bool{return $found['code']===$row[0]&&$found['name_en']===$row[1]&&$found['name_ar']===$row[2]&&$found['location_type']===($parent===null?'COUNTRY':'GOVERNORATE')&&$found['parent_id']===$parent&&$found['status']==='active'&&$found['provenance']==='SYSTEM_SEED'&&(int)$found['sort_order']===$row[3];}
}
